% Where do you want to output the figure?
tmp_suffix = 'gtex'; % type of plot
output_file = strcat('~/autism/doc/pics/aucs_', tmp_suffix, '.png');

% Path to the pre-computed AUCs for each GTEx network
% file format (space-splitted)
% <id> <edge cutoff> <propagatoin steps> <auc>
% example: Brain-cv-001 0.75 5 0.7
% Filenames follow <GTEx tissue>.auc, e.g. Brain.auc
res_dir = '../data/result/gtex/';

% baseline {{{
lcs_baseline = {'ppi', [0 0 0]};
% Path to the pre-computed AUC using PPI network
% file format (space-splitted)
% <id> <edge cutoff> <propagatoin steps> <auc>
% example: ppi-cv-001 0.75 5 0.7
aucs_baseline = {'../data/result/best_network/ppi.auc'};
% }}}

% gtex {{{
gtex = { ...
    'Adipose Tissue', ...
    'Adrenal Gland', ...
    'Bladder', ...
    'Blood', ...
    'Blood Vessel', ...
    'Bone Marrow', ...
    'Brain', ...
    'Breast', ...
    'Cervix Uteri', ...
    'Colon', ...
    'Esophagus', ...
    'Fallopian Tube', ...
    'Heart', ...
    'Kidney', ...
    'Liver', ...
    'Lung', ...
    'Muscle', ...
    'Nerve', ...
    'Ovary', ...
    'Pancreas', ...
    'Pituitary', ...
    'Prostate', ...
    'Salivary Gland', ...
    'Skin', ...
    'Small Intestine', ...
    'Spleen', ...
    'Stomach', ...
    'Testis', ...
    'Thyroid', ...
    'Uterus', ...
    'Vagina', ...
    };

tmp_colors = pfp_cbrewer(3);
lcs_gtex = {...
    'Adipose Tissue',  tmp_colors(2,:); ...
    'Adrenal Gland',   tmp_colors(2,:); ...
    'Bladder',         tmp_colors(2,:); ...
    'Blood',           tmp_colors(2,:); ...
    'Blood Vessel',    tmp_colors(2,:); ...
    'Bone Marrow',     tmp_colors(2,:); ...
    'Brain',           tmp_colors(2,:); ...
    'Breast',          tmp_colors(2,:); ...
    'Cervix Uteri',    tmp_colors(2,:); ...
    'Colon',           tmp_colors(2,:); ...
    'Esophagus',       tmp_colors(2,:); ...
    'Fallopian Tube',  tmp_colors(2,:); ...
    'Heart',           tmp_colors(2,:); ...
    'Kidney',          tmp_colors(2,:); ...
    'Liver',           tmp_colors(2,:); ...
    'Lung',            tmp_colors(2,:); ...
    'Muscle',          tmp_colors(2,:); ...
    'Nerve',           tmp_colors(2,:); ...
    'Ovary',           tmp_colors(2,:); ...
    'Pancreas',        tmp_colors(2,:); ...
    'Pituitary',       tmp_colors(2,:); ...
    'Prostate',        tmp_colors(2,:); ...
    'Salivary Gland',  tmp_colors(2,:); ...
    'Skin',            tmp_colors(2,:); ...
    'Small Intestine', tmp_colors(2,:); ...
    'Spleen',          tmp_colors(2,:); ...
    'Stomach',         tmp_colors(2,:); ...
    'Testis',          tmp_colors(2,:); ...
    'Thyroid',         tmp_colors(2,:); ...
    'Uterus',          tmp_colors(2,:); ...
    'Vagina',          tmp_colors(2,:); ...
    };

aucs_gtex = cell(1, numel(gtex));
for i = 1 : numel(gtex)
    aucs_gtex{i} = sprintf('%s%s.auc', res_dir, gtex{i});
    % aucs_gtex{i}{2} = sprintf('%sx%s.auc', res_dir, gtex{i});
end
% }}}

lcs = [lcs_baseline; lcs_gtex];
aucs = [aucs_baseline aucs_gtex];

barh_compare_auc(output_file, 'Cross-validated AUC of GTEx networks', lcs, aucs{:});
clear tmp_*

% -------------
% Yuxiang Jiang (yuxjiang@indiana.edu)
% Department of Computer Science
% Indiana University, Bloomington
% Last modified: Thu 24 Jul 2021
